spring:
  application:
    name: identity-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/identity}
    username: ${DB_USERNAME:identity}
    password: ${DB_PASSWORD:identity}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true